### ISSUE TITLE
Current Progress

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#14]
1. 1st Phase Wrapup
- We stil have minor communication bug which is only taking data once ( no continuous )
- I suggested to change to I2C protocol between FPGA ILA and Analzyer, so please finalize this one ASAP.

2. 2nd phase kickoff!
- For the 2nd phase, we will focus on the following three items
   1) custom PCB design for FTA Analyzer - We will design have custom board for Zynq APSOC
   2) singal compression stuff - lossy and lossess algorithms will be explored for saving signal storage
   3) We will add more funtionalities for FPGA ILA signals and automatic presynthesizer.

3. TODO
    1) Zhenning and He: You guys need to fix bug asap.
    2) Hui: you need to study more about signal compression schemes and also keep letting me know the PCB design software license.
    3) Monday, we will have PCB tutorial session at 2pm.

Hope you have more productivity in this quarter!

**Comment by tkimva** [comment]
Hope you have made good progress so far. We will see today 2pm for PADS tutorials (PCB design tool). I'll run through schematic and layout tutorials. It might take 2 hrs.

In addition, @hugh-li , please update Prof. Liang's answer which tool our school has for PCB design.

**Comment by hedai** [comment]
Okay，got it！

**Comment by hugh-li** [comment]
OK

发自我的 iPhone

**Comment by Neutrogena** [comment]
Ok, see you at 2
