### ISSUE TITLE
winter week 2 updata

### ISSUE THREAD

**Issue by Neutrogena** [tkimva/fpga_trace_analyzer#15]
What I have done:
Since we change the system and discard the gpio for communication, we don’t have to implement  the interface by ourselves. And we decided to change to using the spi for the board to board communication. So this we what I have done is to make use of the spi module on the ZYNQ PS system. And I finished it about Monday and we spent another two days for debugging and tried the board to board communication. Right now we are trying to make sure the data received by the ZYNQ system is correct.

Problem encountered:
The problem we had right now is that can not make sure the data is correct. and we are trying to fix this problem. We plan to let the target board produce some constant data. We can get some random data like 0x00 or 0xFF and we are trying to figure it out what caused this phenomenon.

Plan next week:
Keeping debugging the system.

**Comment by tkimva** [comment]
Thanks for update
