### ISSUE TITLE
PCB tool

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#25]
All,
Here is good news. Finally, I could get PCB software, it took long time to figure it out as we tried to install first it into our server but it was troublesome as our system team haven't experienced for installation of allegro linux version. So finally Tom help us out to find out our department has windows license too. I'll test it tomorrow.

**Comment by sheldonucr** [comment]
Taeyoung,

That is good news. Thanks for the good efforts.

-Sheldon

Sheldon Tan, Ph.D.
Professor and Graduate Advisor of Computer Engineering Program (CEN)
Dept. of Electrical and Computer Engineering,
University of California,
Riverside, CA 92521
http: www.ece.ucr.edu/~stan<http://www.ece.ucr.edu/~stan>
Tel: 951-827-5143



On Jan 22, 2015, at 5:49 PM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


All,
Here is good news. Finally, I could get PCB software, it took long time to figure it out as we tried to install first it into our server but it was troublesome as our system team haven't experienced for installation of allegro linux version. So finally Tom help us out to find out our department has windows license too. I'll test it tomorrow.

**Comment by tkimva** [comment]
Thanks
