### ISSUE TITLE
Tomorrow Meeting

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#48]
@hedai @Neutrogena @hugh-li 
I think we need to meet tomorrow afternoon to check our progress throughly, so basically how about meeting at 2pm? (2/4)

**Comment by Neutrogena** [comment]
2 is fine for me.

**Comment by hedai** [comment]
Okay，it is fine.

**Comment by hugh-li** [comment]
Okay

发自我的 iPhone
