### ISSUE TITLE
Tomorrow meeting

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#68]
To everyone,

Can we meet 10am tomorrow not 2pm? 

I have been always staying the lab from 8am to 4pm in this quarter. But currently, I'm trouble on allergy and afternoon became more serious, so I would try to avoid staying afternoon in the lab tomorrow.

Please let me know if you have any conflict.

**Comment by hedai** [comment]
But we have EE175 lab section at 10am. It may introduce time conflict.

**Comment by tkimva** [comment]
Then what about 9:30?

**Comment by hedai** [comment]
9:30 is okay.

**Comment by Neutrogena** [comment]
Ok, 9:30 is fine

**Comment by hugh-li** [comment]
OK

**Comment by tkimva** [comment]
Thanks all see you then
