### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by hugh-li** [tkimva/fpga_trace_analyzer#70]
I am not so sure about testing functions. I just think about cursor and extracted original signals.
Do you mean cursor is like this?
![image](https://cloud.githubusercontent.com/assets/9355641/6184995/bbbfdbe2-b31d-11e4-8dcd-598f7c33b1af.png)
And there are different transmission ways for even one protocol, such as I2C and I ask he dai that there is no protocol for his transmission. So I just pick any one to operate extraction in labview?

**Comment by hugh-li** [comment]
Sorry for forgetting post report on github.
Executive Summary
In this project, we design extensive FPGA debugging framework. As the current FPGA debugging solutions (Altera SingalTap/ Xilinx ChipScope) cannot deliver long-term internal signal tracing due to limitation of debugging memory and architecture, we propose new FPGA trace analyzer, which enables dynamically control the signal selection, triggering conditions, and adding operation. The FPGA trace cores work to access the FPGA internal nodes and send the acquired signals through general-purpose input and output pins of FPGAs. The signal traces will be first stored in trace buffer of zynq board. Then signal will be compressed and transmitted to store in 2GB memory of zynq board. Finally the signal will be transferred to PC via Ethernet network connection to FTA waveform display and control GUI.
(key features, testing results, achievements not done)

Design Objectives and System Overview
Describe the concept and application of the design: What are you designing, technical principles, why this is a meaningful project, what are the intended applications, how is it related to subjects in electrical engineering, what are the overall goals of the project.
After a chip is fabricated, failures may happen in the system due to either functional bugs that were undetected during verification or defects that escaped the fabrication test. When the first silicon fails, in-system silicon debug techniques are employed to identify the root cause of these failures. Our new trace analyzer is used to diagnose the undetected design bugs and manufacturing defects by acquiring data using an embedded logic analyzer. However, the trace buffer capacitance limited trace debug testing. So we are designing a logic analyzer with improved memory storage capacitance based on selecting by IP core, storage in trace analyzer board and displaying on labview GUI in PC. And we also use data compression technique to increase storage efficiency.
For our responsibilities, He Dai is in charge of building IP core to select signals inside circuit, compressing trace signal and transferring to storage in zynq board. Zhenning is in charge of receiving compression data and transmitted to labview GUI on PC via building an Ethernet network. Hui is in charge of designing labview GUI to display, controlling and analyzing debug signals, and documentation for everyone. Zhenning and Hui are also working together to make PCB of trace analyzer board to achieving functions of our project.
(Need to add some quantitative technical design objectives)

**Comment by hugh-li** [comment]
Sorry for forgetting to post on github.

Executive Summary
In this project, we design extensive FPGA debugging framework. As the current FPGA debugging solutions (Altera SingalTap/ Xilinx ChipScope) cannot deliver long-term internal signal tracing due to limitation of debugging memory and architecture, we propose new FPGA trace analyzer, which enables dynamically control the signal selection, triggering conditions, and adding operation. The FPGA trace cores work to access the FPGA internal nodes and send the acquired signals through general-purpose input and output pins of FPGAs. The signal traces will be first stored in trace buffer of zynq board. Then signal will be compressed and transmitted to store in 2GB memory of zynq board. Finally the signal will be transferred to PC via Ethernet network connection to FTA waveform display and control GUI.
(key features, testing results, achievements not done)

Design Objectives and System Overview
After a chip is fabricated, failures may happen in the system due to either functional bugs that were undetected during verification or defects that escaped the fabrication test. When the first silicon fails, in-system silicon debug techniques are employed to identify the root cause of these failures. Our new trace analyzer is used to diagnose the undetected design bugs and manufacturing defects by acquiring data using an embedded logic analyzer. However, the trace buffer capacitance limited trace debug testing. So we are designing a logic analyzer with improved memory storage capacitance based on selecting by IP core, storage in trace analyzer board and displaying on labview GUI in PC. And we also use data compression technique to increase storage efficiency.
For our responsibilities, He Dai is in charge of building IP core to select signals inside circuit, compressing trace signal and transferring to storage in zynq board. Zhenning is in charge of receiving compression data and transmitted to labview GUI on PC via building an Ethernet network. Hui is in charge of designing labview GUI to display, controlling and analyzing debug signals, and documentation for everyone. Zhenning and Hui are also working together to make PCB of trace analyzer board to achieving functions of our project.
(Need to add some quantitative technical design objectives)

**Comment by tkimva** [comment]
I told you sync as word file in doc folder with the given format. Please do so
