### ISSUE TITLE
Progress update

### ISSUE THREAD

**Issue by Neutrogena** [tkimva/fpga_trace_analyzer#73]
I googled about slack delay, and how to solve it , but there were not much useful info. So I just checked which signals has negative slack delay. I found out that the signals have this problem are related to the configure port connect between AXI interface and logic input core. So I thought this might be related to the clk synchronize. Because the logic input is running at 200MHz(in order to achieve sample rate @100MHz) and the AXI interface is running @100MHz. I rewrote the logic input core and cut some functions that is not useful for now. And did the simulation, synthesis, and implement. Making the two module running at the same clk speed(but I still have the same sample rate). And now I do not have negative slack. And I am doing testing on board.

**Comment by tkimva** [comment]
Thanks! good work
