### ISSUE TITLE
Friday Demo Prep

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#75]
All,

As you know, there is Demo presentation for your senior design class requirement in this Friday to Prof. Liang. So I want to have a meeting on Thursday instead.

I also have my qualifying exam on Thursday, so it might be better to have a meeting after that, which is around 2pm-5pm on Thursday. Does it work? Let me know when is good.

Thanks
Taeyoung

**Comment by Neutrogena** [comment]
I have a class from 3:40 to 5pm, it might not be a good time.

**Comment by tkimva** [comment]
We just need 30min to have a meeting, so I asked you choose some time
around 2-5pm. How about 2pm?

**Comment by Neutrogena** [comment]
Yeah, 2pm is fine for me

**Comment by hugh-li** [comment]
okay，it's fine 

发自我的 iPhone

**Comment by hedai** [comment]
Yeah，it is okay.
Now I have a personal problem is my laptop's fan does not work two days ago, and I have already hired some guy to repair it. It will be available until at least Friday. Before that I could study some algorithm on the computer of the library.
But I think it may introduce some problems of the Demo presentation.

**Comment by tkimva** [comment]
Let's see 2pm Thursday.
Taeyoung
