### ISSUE TITLE
He Dai

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#80]
From last meeting on Friday, I remember I asked you made PPT for new functionality and done by this Tuesday. I couldn't find any your update here.

**Comment by hedai** [comment]
Sorry by this Tuesday I was preparing for VLSI midterm at that evening. I am just working on it now. Hopefully would finish by tonight.

**Comment by tkimva** [comment]
Tuesday exam already expected. This exam prep cannot be excused. It seems
you forgot this. Please work as scheduled next time.
